#!/usr/bin/python

import os
import sys
import socket
import time
import requests
from random import randint
from ConfigParser import SafeConfigParser

hostname = socket.gethostname()

# ARC job states
arex_job_states = [
    "ACCEPTED",
    "PREPARING",
    "SUBMIT",
    "INLRMS",
    "FINISHING",
    "FINISHED",
    "DELETED",
    "CANCELLING"
]

# Get numbers of jobs in each state
def getJobsStatesInfo():
   control_subdirs = ['accepting', 'finished', 'processing', 'restarting']

   data = ''
   states = {}

   for control_subdir in control_subdirs:
      subdir = os.path.join('/var/spool/arc/jobstatus', control_subdir)

      if not os.path.isdir(subdir):
         return

      try:
         for status_file in os.listdir(subdir):
            try:
               f = open(os.path.join(subdir, status_file))
            except IOError, e:
               print 'Could not open status file %s: %s' % status_file, str(e)
               continue

            status = f.readline().strip()
            if status in states:
               states[status] += 1
            else:
               states[status] = 1
            f.close()
      except OSError, e:
         print 'Could not list status files in %s: %s' % subdir, str(e)

   for state in arex_job_states:
      if state in states:
         value = states[state]
      else:
         value = 0
      data += 'jobs,state=' + state + ',host=' + hostname + ' value=' + str(value) + '\n'

   return data

# Get number of jobs in the processing subdirectory
def getProcessingJobs():
   processing = 0

   processing_dir = '/var/spool/arc/jobstatus/processing'

   try:
      entries = os.listdir(processing_dir)
   except OSError, e:
      print "Error listing dir %s: %s" % processing_dir, str(e)
      return
   processing += len(entries)

   data = 'jobs,state=PROCESSING,host=' + hostname + ' value=' + str(processing) + '\n'
   return data

# Get the time since the modification timestamp of the gm-heartbeat file
def getHeartBeatInfo():

   heartbeat = '/var/spool/arc/jobstatus/gm-heartbeat'
   try:
      statinfo = os.stat(heartbeat)
   except OSError, e:
      print "Error with heartbeat file: %s" %str(e)
      return

   mtime = statinfo.st_mtime
   now = time.time()
   heartbeat_time = now - mtime

   data = 'arex_heartbeat_lastseen,host=' + hostname + ' value=' + str(heartbeat_time) + '\n'
   return data

# Read from config file
parser = SafeConfigParser()
try:
   parser.read('/usr/local/etc/influxdb-arc.conf')
   hostsInflux = parser.get('db', 'host')
   database = parser.get('db', 'database')
   username = parser.get('auth', 'username')
   password = parser.get('auth', 'password')
except:
   raise NameError('Unable to read from config file')

data = ''

# Generate metrics
data += getJobsStatesInfo()
data += getProcessingJobs()
data += getHeartBeatInfo()

# Send to InfluxDB - if multiple hosts are defined, pick a random host. If this fails,
# repeat until we have success
hosts = hostsInflux.split(',')
success = False
while not success:
   pick = randint(0,len(hosts)-1)
   statuscode = 0
   try:
      r = requests.post('http://'+hosts[pick]+'/write?db='+database, auth=(username, password), data=data, timeout=40)
      statuscode = r.status_code
   except:
      print 'ERROR: Problem connecting to',hosts[pick]
   if statuscode == 204:
      success = True
   else:
      hosts.remove(hosts[pick])
      if len(hosts) == 0:
         raise NameError('Unable to send metrics to InfluxDB')
         
