#!/usr/bin/python
import classad
import htcondor

coll = htcondor.Collector()
results = coll.query(htcondor.AdTypes.Startd, 'PartitionableSlot == TRUE && NODE_STATUS =!= DEFINED && NODE_STATUS =!= "All_OK"', ["NODE_STATUS"])

countCvmfsALICE = 0
countCvmfsATLAS = 0
countCvmfsLHCb = 0
countCvmfsCMS = 0
countCvmfsGRID = 0

for result in results:
   if 'alice' in result["NODE_STATUS"]:
      countCvmfsALICE += 1
   if 'atlas' in result["NODE_STATUS"]:
      countCvmfsATLAS += 1
   if 'cms' in result["NODE_STATUS"]:
      countCvmfsCMS += 1
   if 'lhcb' in result["NODE_STATUS"]:
      countCvmfsLHCb += 1
   if 'grid' in result["NODE_STATUS"]:
      countCvmfsGRID += 1

data = 'wn-problems,type=cvmfs-alice value='+str(countCvmfsALICE)+'\n'
data = data + 'wn-problems,type=cvmfs-atlas value='+str(countCvmfsATLAS)+'\n'
data = data + 'wn-problems,type=cvmfs-cms value='+str(countCvmfsCMS)+'\n'
data = data + 'wn-problems,type=cvmfs-lhcb value='+str(countCvmfsLHCb)+'\n'
data = data + 'wn-problems,type=cvmfs-grid value='+str(countCvmfsGRID)+'\n'

print data
